INSERT INTO Users (id, login, email) VALUES (1, 'login1', 'email1@com.pl')
INSERT INTO Users (id, login, email) VALUES (2, 'login2', 'email2@com.pl')

INSERT INTO Prelections (id, start_hour, name) VALUES(1, '10:00', '1.1')
INSERT INTO Prelections (id, start_hour, name) VALUES(2, '10:00', '1.2')
INSERT INTO Prelections (id, start_hour, name) VALUES(3, '10:00', '1.3')
INSERT INTO Prelections (id, start_hour, name) VALUES(4, '12:00', '2.1')
INSERT INTO Prelections (id, start_hour, name) VALUES(5, '12:00', '2.2')
INSERT INTO Prelections (id, start_hour, name) VALUES(6, '12:00', '2.3')
INSERT INTO Prelections (id, start_hour, name) VALUES(7, '14:00', '3.1')
INSERT INTO Prelections (id, start_hour, name) VALUES(8, '14:00', '3.2')
INSERT INTO Prelections (id, start_hour, name) VALUES(9, '14:00', '3.3')
