--INSERT INTO Users (id, login, email) VALUES (1, 'login1', 'email1@com.pl')
--INSERT INTO Users (id, login, email) VALUES (2, 'login2', 'email2@com.pl')

INSERT INTO Prelections (id, start_hour, name) VALUES(1, '10:00', 'Java')
INSERT INTO Prelections (id, start_hour, name) VALUES(2, '10:00', 'Python')
INSERT INTO Prelections (id, start_hour, name) VALUES(3, '10:00', 'C#')
INSERT INTO Prelections (id, start_hour, name) VALUES(4, '12:00', 'Java')
INSERT INTO Prelections (id, start_hour, name) VALUES(5, '12:00', 'Python')
INSERT INTO Prelections (id, start_hour, name) VALUES(6, '12:00', 'C#')
INSERT INTO Prelections (id, start_hour, name) VALUES(7, '14:00', 'Java')
INSERT INTO Prelections (id, start_hour, name) VALUES(8, '14:00', 'Python')
INSERT INTO Prelections (id, start_hour, name) VALUES(9, '14:00', 'C#')
