INSERT INTO Users (id, login, email) VALUES ((SELECT NEXT VALUE FOR hibernate_sequence), 'login1', 'email1@com.pl')
INSERT INTO Users (id, login, email) VALUES ((SELECT NEXT VALUE FOR hibernate_sequence), 'login2', 'email2@com.pl')
INSERT INTO Users (id, login, email) VALUES ((SELECT NEXT VALUE FOR hibernate_sequence), 'login3', 'email3@com.pl')
INSERT INTO Users (id, login, email) VALUES ((SELECT NEXT VALUE FOR hibernate_sequence), 'login4', 'email4@com.pl')
INSERT INTO Users (id, login, email) VALUES ((SELECT NEXT VALUE FOR hibernate_sequence), 'login5', 'email5@com.pl')
INSERT INTO Users (id, login, email) VALUES ((SELECT NEXT VALUE FOR hibernate_sequence), 'login6', 'email6@com.pl')
INSERT INTO Reservations(user_id, prelection_id) VALUES (1, 1)
INSERT INTO Reservations(user_id, prelection_id) VALUES (3, 1)
INSERT INTO Reservations(user_id, prelection_id) VALUES (4, 1)
INSERT INTO Reservations(user_id, prelection_id) VALUES (5, 1)
INSERT INTO Reservations(user_id, prelection_id) VALUES (6, 1)
INSERT INTO Reservations(user_id, prelection_id) VALUES (1, 4)
INSERT INTO Reservations(user_id, prelection_id) VALUES (1, 8)
INSERT INTO Reservations(user_id, prelection_id) VALUES (2, 2)
INSERT INTO Reservations(user_id, prelection_id) VALUES (2, 4)
